### ISSUE TITLE
请教一下为什么我无法转换B站弹幕呢？提示：ValueError: Unknown comment file format

### ISSUE THREAD

**Issue by tea321000** [m13253/BiliDan#67]
以下命令行转换NICONICO弹幕可以正常完成，但是转换B站字幕时会报错，提示：ValueError: Unknown comment file format，请教一下这是为什么呢？以下是报错信息：
D:\danmaku2ass-master\danmaku2ass.py -o "1 (2).ass" -
s 1920x1080 -fn "微软雅黑" -fs 45 -a 0.8 -dm 5 -ds 5 "1 (2).xml"
Traceback (most recent call last):
  File "D:\danmaku2ass-master\danmaku2ass.py", line 870, in <modu
le>
    main()
  File "D:\danmaku2ass-master\danmaku2ass.py", line 866, in main
    Danmaku2ASS(args.file, args.output, width, height, args.protect, args.font,
args.fontsize, args.alpha, args.duration_marquee, args.duration_still, args.redu
ce)
  File "D:\danmaku2ass-master\danmaku2ass.py", line 802, in Danma
ku2ASS
    comments = ReadComments(input_files, font_size)
  File "D:\danmaku2ass-master\danmaku2ass.py", line 831, in ReadC
omments
    raise ValueError(_('Unknown comment file format: %s') % i)
ValueError: Unknown comment file format: 1 (2).xml

**Comment by m13253** [comment]
联动 https://github.com/m13253/danmaku2ass/issues/36
